baseURL = "https://beeligul.42.fr/info"
theme = "shell"
paginate = 8
canonifyURLs = true

[params]
	
	[Params.Terminal]
		schema = "gruvbox_dark"

	userName = "beeligul"
	pcName = "debian"
	workDir = "ben"
	
	description = """
	Hi...
	I Am Berkay Eligul
	This is My Portfolio!
	
	"""
	
	[Params.Tree]
	use = true
	files = [
	["Unity", ""],
	["Python", "https://python.org/"],
	["Django", ""],
	["Hugo", "https://gohugo.io/"],
	["Docker", ""],
	
	]
