CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'beeligul'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'beeligul'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '123';
